[package]
name = "exifgeo"
version = "0.1.0"
authors = ["Vadim Bendebury <vbendeb@chromium.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
arrayvec = "0.7.1"
zerocopy = "0.6"
